---
title: "Tarea 5"
output:
  html_document:
    df_print: paged
---

#Pregunta 2
```{r}
library(ggplot2)
library(tidyverse)
library(dplyr)



```


```{r}
library(gridExtra)
library(ggplot2)
library(ggthemes)
library(tidyquant)
library(forcats)
library(lubridate)
library(quantmod)
```


```{r}
MICROSOFT <- tq_get("MSFT",
                    get = "stock.prices",
                    from = "2000-01-01",
                    to = "2018-08-31",
                    periodicity = "monthly")

APPLE <- tq_get("AAPL",
                get = "stock.prices",
                from = "2000-01-01",
                to = "2018-08-31",
                periodicity = "monthly")

Acciones <- c("MSFT","AAPL")
data_Acciones <- tq_get(Acciones,
                        get = "stock.prices",
                        from = "2000-01-01",
                        to  = "2018-08-30",
                        periodicity = "monthly")



retorno <- function(x, return=c('yes','no'),plot=c('type 1', 'type 2'), normal =c('yes','no')) {
  data <- x
  g <- 0
  if(return == 'yes'){
    data$retorno = 0
    data$acumulado = 0
    
    ajustado <- data$adjusted 
    logajustado= diff(log(ajustado),lag=1)
    retorno = data.frame(rbind(0,data.frame(logajustado)))
    data$retorno = retorno[,1]
    data$acumulado <- cumsum(data$retorno)
    
    
    
    
    if(plot=='type 1'){
      g <- data %>% ggplot(mapping= aes(x=retorno))+
        geom_density(alpha=0.5) + scale_fill_tq() 
    }
    if(plot == 'type 2'){
      g <- data %>% ggplot (mapping = aes(x= date, y= acumulado)) +
        geom_line()+ theme_tq()
    }
  }
  
  
  if (return == 'no') {
    data$retorno = NA
    data$acumulado = NA
    
    ajustado <- data$adjusted 
    retorno = ((rbind(0,data.frame(diff(ajustado,lag=1))))/(ajustado-rbind(0,data.frame(diff(ajustado,lag=1)))))
    data$retorno = retorno[,1]
    data$acumulado <- cumsum(data$retorno)
    
    if(plot== 'type 1'){
      g <- data %>% ggplot(mapping= aes(x=retorno))+
        geom_density(alpha=0.5) + scale_fill_tq() 
    }
    if(plot == 'type 2'){
      g <- data %>% ggplot (mapping = aes(x= date, y= acumulado)) +
        geom_line()+ theme_tq()
    }
    
  }
  
  n <- nrow(data)
  mean = sum(data$retorno)/n
  s = ((sum(data$retorno-mean)^3)/n)/((sum(data$retorno-mean)^2)/n)^(3/2)
  k = ((sum(data$retorno-mean)^4)/n)/((sum(data$retorno-mean)^2)/n)^2
  JB = n*(((s^2)/6)+(((k-3)^2)/24))
  if(normal == 'yes'){
    if(1 - pchisq(JB,df = 2)<0.05){
      m <- cat("JB =",JB,", P-value =",1 - pchisq(JB,df = 2),", Se rechaza la hipotesis nula de normalidad")
      
    } else{
      m <- cat("JB =",JB,", P-value =",1 - pchisq(JB,df = 2),", No se rechaza la hipotesis nula de normalidad")}
  }
  
  
  
  return(g)
}


retorno(APPLE,"yes","type 1","yes")
retorno(APPLE,"yes","type 2","yes")

retorno(MICROSOFT,"yes","type 1","yes")
retorno(MICROSOFT,"yes","type 2","yes")
```

#PREGUNTA 3

##a) Esperanza y Varianza para muestras de 50, 100, 500 y 1000. ¿Existe sesgo? ¿Desaparece el sesgo a medida que la muestra aumenta?

```{r}
library(gridExtra)
library(foreign)
library(stargazer)
library(dplyr)
library(car)
library(tidyquant)
library(ggplot2)

```


```{r}

set.seed(123)
reps=10000
BETA1=matrix(NA, nrow= reps, ncol=16)
BETA2=matrix(NA, nrow= reps, ncol=16)
beta0=2
beta1=2.5
beta2=1
su=1
n = c(50, 100, 500, 1000) #Tamaño Muestral
for(j in 1:length(n)) {
  x1=rnorm(n[j],20,1)
  x2a=(0.8*x1)+rnorm(n[j],0,1)
  x2b=runif(n[j],0,1)
  
  for(i in 1:reps){
    u=rnorm(n[j],0,su)
    v1= (beta2*x2a)+ u
    v2= (beta2*x2b)+ u
    
    Y0=beta0+beta1*x1 + v1
    Y1=beta0 + beta1*x1 + beta2*x2a + u
    Y2=beta0+beta1*x1 + v2
    Y3=beta0 + beta1*x1 + beta2*x2b + u
    model0= lm(Y0~x1)
    BETA1[i,j] =model0$coef[1] #beta0 modelo sesgado
    BETA1[i,j+4] =model0$coef[2] #beta1 modelo sesgado
    model1= lm(Y1~x1 +x2a)
    BETA1[i,j+8] = model1$coef[1] #beta0 modelo correcto
    BETA1[i,j+12] = model1$coef[2] #beta1 modelo correcto
    
    model2 <- lm(Y2~x1)
    BETA2[i,j] =model2$coef[1] #beta0 modelo sesgado
    BETA2[i,j+ 4] =model2$coef[2] #beta1 modelo sesgado
    model3= lm(Y3~x1 +x2b)
    BETA2[i,j+8] = model2$coef[1] #beta0 modelo correcto
    BETA2[i,j+12] = model2$coef[2] #beta1 modelo correcto
    
  }
}



dataBETA1 = data.frame(BETA1)
dataBETA2 = data.frame(BETA2)

# media

betas1 <-c(apply(dataBETA1, 2, mean))
betas2 <-c(apply(dataBETA2, 2, mean))
betas <- cbind(betas1,betas2)
betas


# varianza

apply(dataBETA1, 2, var)
apply(dataBETA2, 2, var)

varianzas1 <-c(apply(dataBETA1, 2, var))
varianzas2 <-c(apply(dataBETA2, 2, var))
varianzas <- cbind(varianzas1,varianzas2)



```

##b) Grafique la distribución de B1 de los n


```{r}

grafico_ses50=ggplot(dataBETA1) + 
  geom_histogram(aes(dataBETA1[,5],y=..density..), col="black", bins = 30) +
  stat_function(fun = dnorm, args = list(mean=mean(dataBETA1[,5]), sd=sd(dataBETA1[,5])),
                geom = "line", color="blue", size=1) +
  ylab("Density") + ggtitle("Muestra 50: Modelo con multicolinealidad") +xlab(expression(hat(beta)[1])) +
  theme_bw()

grafico_inses50=ggplot(dataBETA1) + 
  geom_histogram(aes(dataBETA1[,13],y=..density..), col="black", bins = 30) +
  stat_function(fun = dnorm, args = list(mean=mean(dataBETA1[,13]), sd=sd(dataBETA1[,13])),
                geom = "line", color="blue", size=1) +
  ylab("Density") + ggtitle("Muestra 50: Modelo sin multicolinealidad") +xlab(expression(hat(beta)[1])) +
  theme_bw()

n50=grid.arrange(grafico_ses50, grafico_inses50, ncol=1)


#muestra 100


grafico_ses100=ggplot(dataBETA1) + 
  geom_histogram(aes(dataBETA1[,6],y=..density..), col="black", bins = 30) +
  stat_function(fun = dnorm, args = list(mean=mean(dataBETA1[,6]), sd=sd(dataBETA1[,6])),
                geom = "line", color="red", size=1) +
  ylab("Density") + ggtitle("Muestra 100: Modelo con multicolinealidad") +xlab(expression(hat(beta)[1])) +
  theme_bw()

grafico_inses100=ggplot(dataBETA1) + 
  geom_histogram(aes(dataBETA1[,14],y=..density..), col="black", bins = 30) +
  stat_function(fun = dnorm, args = list(mean=mean(dataBETA1[,14]), sd=sd(dataBETA1[,14])),
                geom = "line", color="red", size=1) +
  ylab("Density") + ggtitle("Muestra 100: Modelo sin multicolinealidad") +xlab(expression(hat(beta)[1])) +
  theme_bw()

n100= grid.arrange(grafico_ses100, grafico_inses100, ncol=1)

#muestra 500

grafico_ses500=ggplot(dataBETA1) + 
  geom_histogram(aes(dataBETA1[,7],y=..density..), col="black", bins = 30) +
  stat_function(fun = dnorm, args = list(mean=mean(dataBETA1[,7]), sd=sd(dataBETA1[,7])),
                geom = "line", color="red", size=1) +
  ylab("Density") + ggtitle("Muestra 500: Modelo con multicolinealidad") +xlab(expression(hat(beta)[1])) +
  theme_bw()

grafico_inses500=ggplot(dataBETA1) + 
  geom_histogram(aes(dataBETA1[,15],y=..density..), col="black", bins = 30) +
  stat_function(fun = dnorm, args = list(mean=mean(dataBETA1[,15]), sd=sd(dataBETA1[,15])),
                geom = "line", color="red", size=1) +
  ylab("Density") + ggtitle("Muestra 500: Modelo sin multicolinealidad") +xlab(expression(hat(beta)[1])) +
  theme_bw()

n500= grid.arrange(grafico_ses500, grafico_inses500, ncol=1)

#muestra 1000

grafico_ses1000=ggplot(dataBETA1) + 
  geom_histogram(aes(dataBETA1[,16],y=..density..), col="black", bins = 30) +
  stat_function(fun = dnorm, args = list(mean=mean(dataBETA1[,16]), sd=sd(dataBETA1[,16])),
                geom = "line", color="red", size=1) +
  ylab("Density") + ggtitle("Muestra 1000: Modelo con multicolinealidad") +xlab(expression(hat(beta)[1])) +
  theme_bw()


grafico_inses1000=ggplot(dataBETA1) + 
  geom_histogram(aes(dataBETA1[,16],y=..density..), col="black", bins = 30) +
  stat_function(fun = dnorm, args = list(mean=mean(dataBETA1[,16]), sd=sd(dataBETA1[,16])),
                geom = "line", color="red", size=1) +
  ylab("Density") + ggtitle("Muestra 1000: Modelo sin multicolinealidad") +xlab(expression(hat(beta)[1])) +
  theme_bw()
g4= grid.arrange(grafico_ses1000, grafico_inses1000, ncol=1)




```

##c) Si X2 distr unif ¿Como se distribuyen los datos en a y b?



```{r}

```

